# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:
  bmo:
    image: mozillaconduit/docker-bmo
    ports:
      - "7777:80"
    volumes:
      - bmo-mysql-db:/var/lib/mysql

  demo:
    build:
      context: docker/vct-hg
      dockerfile: ./Dockerfile
    volumes:
      - .:/root/repo:ro
    depends_on:
      - phabricator.dev
      - bmo

  phabricator:
    image: mozilla/mozphab
    environment:
      - MYSQL_HOST=phabdb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - PHABRICATOR_URI=http://phabricator.dev:7788/
    restart: on-failure
    depends_on:
      - phabdb

  # Use '.dev' in the name so 'phabricator.dev' resolves to the correct
  # IP both inside and outside the docker-compose network.
  phabricator.dev:
    image: nginx:alpine
    ports:
      - "7788:80"
    volumes:
      - ./docker/phabricator/site.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - phabricator
    depends_on:
      - phabricator

  phabdb:
    image: mysql:5.5
    volumes:
      - phabricator-mysql-db:/var/lib/mysql
      - ./docker/phabricator/mysql:/etc/mysql/conf.d:ro
      - ./docker/phabricator/demo.sql.gz:/docker-entrypoint-initdb.d/demo.sql.gz
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  bmo-mysql-db:
  phabricator-mysql-db:
